name: CI - Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-html uvicorn

      # 👇 Start FastAPI app before tests
      - name: Start FastAPI server
        run: |
          nohup uvicorn app.server:app --host 127.0.0.1 --port 8000 &
          sleep 5   # wait for server to be ready

      - name: Run tests
        run: |
          mkdir -p reports
          PYTHONPATH=. pytest tests/ -v --junitxml=reports/junit.xml \
                          --html=reports/report.html --self-contained-html

      # 👇 Kill server after tests
      - name: Stop FastAPI server
        if: always()
        run: |
          kill -9 $(cat uvicorn_pid.txt)

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-artifacts
          path: reports/

 # --- GitHub Pages Deployment ---
      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4