name: CI - Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-html

      - name: Run tests
        run: |
          mkdir -p reports
          pytest tests/ -v --junitxml=reports/junit.xml \
                        --html=reports/report.html --self-contained-html

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-artifacts
          path: reports/
